name: dbt Snowflake Pipeline

on:
  push:
    branches:
      - main

  schedule:
    - cron: '0 * * * *'

jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt Snowflake
        run: |
          pip install dbt-snowflake

      - name: Create dbt profile
        run: |
          mkdir -p ~/.dbt

          cat > ~/.dbt/profiles.yml << EOF
          keyvan:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
                user: ${{ secrets.SNOWFLAKE_USER }}
                password: ${{ secrets.SNOWFLAKE_PASSWORD }}
                role: ${{ secrets.SNOWFLAKE_ROLE }}
                warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
                database: ${{ secrets.SNOWFLAKE_DATABASE }}
                schema: bronze
                threads: 1
          EOF

      - name: Install dbt packages
        run: dbt deps

      - name: Run dbt build
        run: dbt build
